[package]
name = "ribbon"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
authors = ["memothelemo <memothelemo@protonmail.com>"]

[dependencies]
ribbon_api = { path = "./crates/api" }
tokio = { version = "1.21.2", features = ["full"] }
