[package]
name = "ribbon-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.8.5", features = ["luau"] }
once_cell = "1.16.0"
rand = "0.8.5"
serde = "1.0.147"
serde_json = "1.0.87"
uuid = { version = "1.2.1", features = ["v4"] }
